### ISSUE TITLE
AFC-1275 - Make a Fenix Sprint Branch and Upgrade the Fossa-server

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#312]
**Userstory:** 
As a developer I want a Sprint Development branch for Fenix-server based on the Current version of Dev-12.0-branch in each Repository.

**Tasks**
1 I want the code below to be merged into the "Dev-12.0-Fenix-branch"
2 As a user, I want Fossa to be upgraded with the "Dev-12.0-Fenix-branch"
3 Install the modules on "Fenix_t02"-database on Fossa.
https://fossa.vertel.se/web?db=Fenix_t02

ssh miracle@fossa.vertel.se
Web-interface: https://fossa.vertel.se/web/database/selector

**Branch names** 
https://github.com/vertelab/odoo-af/pull/278 Module:  af_sale_orders
renamed and moved to odoo-sale/af_sale_orders

https://github.com/vertelab/odoo-af/pull/279 Module:  af_impaired_portal_ui
https://github.com/vertelab/odoo-af/pull/290 Module: af_backend_tema
https://github.com/vertelab/odoo-af/pull/295 Module: af_backend_tema

https://github.com/vertelab/odoo-af/pull/298 Module: af_order_report
renamed and moved to odoo-sale/af_order_report

https://github.com/vertelab/odoo-af/pull/289 Module: af_mail_client_contact
renamed and moved to odoo-mail/af_mail_client_contact

https://github.com/vertelab/odoo-af/pull/311 Module: fenix_dashboard
https://github.com/vertelab/odoo-af/pull/280 Module: af_automatic_customer_dialogue
renamed and moved to odoo-mail/af_automatic_customer_dialogue

https://github.com/vertelab/odoo-hr/pull/11 Module: hr_employee_customers_tab
renamed and moved to odoo-hr/hr_employee_customers_tab

https://github.com/vertelab/odoo-project/pull/1 Module:  project_jobseeker_views

**Estimate:** (added by developers only)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by iammiracle** [comment]
Just to be clear, you mean you want those modules to be merged into the Dev-12.0-Fenix-Sprint-02 branch right?

**Comment by FredrikArvas** [comment]
yes, in the appropriate repository and then the new branch!

**Comment by iammiracle** [comment]
Hi Fredrik, I was blocked at this

![image](https://user-images.githubusercontent.com/7355805/97811881-c0703180-1c7d-11eb-95b9-1003ec31b1eb.png)

I have created a new branch with the above modules, but at the point of git pulling on the server, i got that error.

Then I will need credentials to login to the server

**Comment by FredrikArvas** [comment]
@nils-vertel  could you please assist Miracle with the access to the server

**Comment by nils-vertel** [comment]
Rights should be fixed now. @iammiracle please verify

**Comment by iammiracle** [comment]
![image](https://user-images.githubusercontent.com/7355805/97857872-a32f7780-1cfe-11eb-8d47-c008f6ace771.png)

Still having the issues

**Comment by nils-vertel** [comment]
I checked on your account at Fossa and you have not generated any ssh keys.
Run ssh-keygen to generate new keys, just press enter on all questions.
Then add your public key content (~/.ssh/id_rsa.pub) to github

**Comment by iammiracle** [comment]
I have added my public key to github, but the old public that does not have access has been added to the server, I don't know if any other person has the public key on the server, so i dont delete the ~/.ssh/known_hosts. What do you think @nils-vertel

**Comment by iammiracle** [comment]
After adding the public key to github and deleting the known hosts, I added my fingerprint again and this is what I got.

![image](https://user-images.githubusercontent.com/7355805/97865827-1a6b0880-1d0b-11eb-8ad7-2f980969eb8e.png)

@FredrikArvas the other option is if @nils-vertel can pull from the [new branch I created](https://github.com/vertelab/odoo-af/tree/Dev-12.0-Fenix-branch) the modules have been merged there and the checkout branch has been done on the server.

So if this can be done and server restarted, I can login to the database and install the modules

**Comment by FredrikArvas** [comment]
@anderswallenquist Miracle sais he still has problems: 
![2020-11-02](https://user-images.githubusercontent.com/9428370/97911707-05629980-1d4c-11eb-83fe-b3d3d80b9adb.png)

**Comment by anderswallenquist** [comment]
sudo chown odoo:odoo -R .

After that I could sudo su miracle and git pull origin Dev-12.0-Fenix-Sprint-02

**Comment by FredrikArvas** [comment]
It is so easy when you know what to do....
Just get help from an expert!

**Comment by FredrikArvas** [comment]
Thanks @anderswallenquist

**Comment by FredrikArvas** [comment]
It looks like the server is working now (I created a new database)

**Comment by FredrikArvas** [comment]
I have installed all modules but get errors on these ones:
@rupareliyahemangi145 af_backend_tema: Uncaught Error: QWeb2: Template 'af_web_theme.AppsBarMenu' not found
@iammiracle hr_employee_customers_tab = not found
@iammiracle project_jobseeker_views = not found

**Comment by iammiracle** [comment]
I did not want to bring this in before, because it means modules from the odoo-hr and odoo-project will be included in the branch Dev-12.0-Fenix-Sprint-02 of odoo-af repo, but I have done that and it is now on the server, the server can be restarted and you will the see the modules.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas  I will check it.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've pushed code in Dev-12.0-Fenix-Sprint-02 branch to solve af_backend_tema: Uncaught Error: QWeb2: Template 'af_web_theme.AppsBarMenu' not found error.

Please check it and let me know if anything.
