### ISSUE TITLE
AFC-1007_depencency_column_in_App_tree-view

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#412]
**Userstory:** 
As a user, I want to see the modules dependencies in the tree view, and when I click on the dependent module, I want that modules line to be in focus. 
As a user I want to be able to search on the depencencies_id in the search-box

**Screen-shots with changes:** (illustration of proposed changes)
![image](https://user-images.githubusercontent.com/9428370/100385968-6c5e3000-3024-11eb-8f3c-e7eeb892435b.png)
![image](https://user-images.githubusercontent.com/9428370/100399501-5a47b600-3053-11eb-9bdf-bdc16fe7b445.png)

**Module name:** 
odoo-base/base_module-depends_widget

**Branch name:** 
Dev-12.0-DAFA-Sprint-02-AFC-1XXX-...

**Module type:** 
Property module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Test-steps:**
Install the module
Click on Apps -> Tree View
On the line of "contacts"-module  -> Click on "mail" in the dependency column. 
Then the module with the technical name "mail" should be visible
![image](https://user-images.githubusercontent.com/9428370/100386277-340b2180-3025-11eb-83c8-69acaf6ec20e.png)

**Description to the manifest:** 
This module displays the Depends-field in the tree-view with a widget that lets users click through the hiearchy of dependencies.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 20mins

**Comment by iammiracle** [comment]
Hi @FredrikArvas I can see you have dependency column already, which module adds this column

**Comment by FredrikArvas** [comment]
Hi, 
I have only added them thorugh the "bug"->Edit view.

Please add a new module: 

Module name:
odoo-base/base_module-depends_widget

**Comment by iammiracle** [comment]
Hi @FredrikArvas I have added the dependencies in the tree view but the ability to make it clickable will require me to develop a widget.

Should I proceed with this?

**Comment by FredrikArvas** [comment]
Hi @iammiracle 
Please push this version now and we can prioritize the widget later. 

I would like you to start with this issue: 
https://github.com/vertelab/odoo-af/issues/176

It is urgent and it has been with an other developer for some time. 
They might have done something about it, but we do not know. 
So I would like you to start with it if you have time today.

Thanks

**Comment by iammiracle** [comment]
[PR Created](https://github.com/vertelab/odoo-base/pull/169)

**Comment by FredrikArvas** [comment]
Hi @iammiracle 
Could you please make a new PR, with only the new module?
(possibly from a fresh branch).

**Comment by iammiracle** [comment]
@FredrikArvas [PR Created](https://github.com/vertelab/odoo-base/pull/170)

**Comment by FredrikArvas** [comment]
Thanks @iammiracle 
I would like you to update this with these changes
1 only include files that you have changed in this issue 
2 add a name of the module in the manifest that correspnods to the folder-name
3 add the description from the gitissue to the description in the manifest
4 add an image of the added feature in the PR-comment.
5 Add spent time
Please make a new PR.

This will help for the next person in the workflow.

**Comment by FredrikArvas** [comment]
(It looks like you created your development branch from Dev-12.0 instead of Dev-12.0-Fenix...-branch, because you also got changes that were made in Dev-12-branch in your PR.)

**Comment by iammiracle** [comment]
I updated the PR

![image](https://user-images.githubusercontent.com/7355805/100498197-cfed7800-3160-11eb-9137-d88146eb5f9c.png)

**Comment by FredrikArvas** [comment]
Thanks @iammiracle 
But I still see new files in the PR
https://github.com/vertelab/odoo-base/pull/170/files

I think you need to copy the folder with the new module out of the branch. Then close the current branch.
Create a new branch (from Fenix-branch)
Then move the copy into the new branch
Then commit and create PR.

![image](https://user-images.githubusercontent.com/9428370/100498597-9ff3a400-3163-11eb-9519-9f8d742b8d41.png)
![image](https://user-images.githubusercontent.com/9428370/100498601-b3067400-3163-11eb-9292-487c3a10d22f.png)
![image](https://user-images.githubusercontent.com/9428370/100498611-bef23600-3163-11eb-87c3-9f3f3b3ae89b.png)
![image](https://user-images.githubusercontent.com/9428370/100498613-c87b9e00-3163-11eb-9def-50ac66ecced3.png)

**Comment by iammiracle** [comment]
New [PR Created](https://github.com/vertelab/odoo-base/pull/171)

This should be okay now

**Comment by arturchilangwa-vertel** [comment]
@FredrikArvas 
The code for this issue is merged in https://github.com/vertelab/odoo-base/pull/171.
